import type { ClassDef, ClassId } from "../types";

export const CLASSES: ClassDef[] = [
  {
    id: "vanguard",
    name: "Akıncı",
    role: "Yakın baskı",
    description: "Saçma namlu, yüksek can. Düşmanın içine girip dağıtır.",
    ultName: "Yıkım Dalgası",
    ultBlurb: "Etrafındaki herkesi savurur. Dalga ilerledikçe yarıçap ve hasar artar.",
    color: "#ff8a4a",
    preferredBoostIds: ["shotgun", "heavy", "knockback", "hp", "multishot", "pierce"],
    passive: { id: "berserker_rage", name: "Rage", description: "Can %40'ın altındayken hasar artar." },
    ult: { kind: "nova", baseCooldown: 14 },
    stats: {
      moveSpeed: 255,
      fireRate: 5.4,
      projectileSpeed: 470,
      projectileDamage: 9,
      projectilePierce: 0,
      projectileCount: 3,
      maxHp: 130,
      armor: 0,
      dodge: 0,
      shield: 0,
      spread: 0.15,
      knockback: 95,
      recoil: 14,
      critChance: 0.05,
      critMultiplier: 1.7,
      burstCount: 1,
      lifesteal: 0,
      ricochet: 0,
      explosionRadius: 0,
      slowFactor: 0,
      slowDuration: 0,
      regenPerSecond: 0,
      xpGain: 1,
      goldGain: 1,
      dropChance: 1,
      rerollCharges: 0,
      damageTakenMultiplier: 1,
    },
  },
  {
    id: "marksman",
    name: "Nişancı",
    role: "Uzun menzil",
    description: "Tek, sert ve isabetli mermi. Kritik ve delme ile büyür.",
    ultName: "Kırılma Işını",
    ultBlurb: "Nişan hattındaki herkesi delen ışın. Seviye ile uzunluk ve hasar artar.",
    color: "#4cc9f0",
    preferredBoostIds: ["damage", "accuracy", "velocity", "crit", "critdmg", "pierce"],
    passive: { id: "deadeye", name: "Deadeye", description: "Kritik vuruşlar bir ek delme kazanır." },
    ult: { kind: "beam", baseCooldown: 13 },
    stats: {
      moveSpeed: 225,
      fireRate: 4.1,
      projectileSpeed: 800,
      projectileDamage: 18,
      projectilePierce: 1,
      projectileCount: 1,
      maxHp: 90,
      armor: 0,
      dodge: 0,
      shield: 0,
      spread: 0.016,
      knockback: 32,
      recoil: 8,
      critChance: 0.18,
      critMultiplier: 2.15,
      burstCount: 1,
      lifesteal: 0,
      ricochet: 0,
      explosionRadius: 0,
      slowFactor: 0,
      slowDuration: 0,
      regenPerSecond: 0,
      xpGain: 1,
      goldGain: 1,
      dropChance: 1,
      rerollCharges: 0,
      damageTakenMultiplier: 1,
    },
  },
  {
    id: "warden",
    name: "Teknisyen",
    role: "Kontrol",
    description: "Yavaşlatma ve seken mermi. Alanı kilitleyip aşındırır.",
    ultName: "Kuantum Kapanı",
    ultBlurb: "Nişan noktasına yavaşlatan alan koyar. Süre ve yarıçap dalgayla büyür.",
    color: "#b794f6",
    preferredBoostIds: ["frost", "ricochet", "explosive", "regen", "lifesteal", "adrenaline"],
    passive: { id: "elemental_attunement", name: "Elemental Attunement", description: "Yavaşlatılmış düşmanlara karşı hasar artar." },
    ult: { kind: "zone", baseCooldown: 15 },
    stats: {
      moveSpeed: 235,
      fireRate: 6.1,
      projectileSpeed: 560,
      projectileDamage: 10,
      projectilePierce: 0,
      projectileCount: 1,
      maxHp: 110,
      armor: 0,
      dodge: 0,
      shield: 0,
      spread: 0.05,
      knockback: 42,
      recoil: 9,
      critChance: 0.08,
      critMultiplier: 1.8,
      burstCount: 1,
      lifesteal: 0,
      ricochet: 1,
      explosionRadius: 0,
      slowFactor: 0.32,
      slowDuration: 0.75,
      regenPerSecond: 1.2,
      xpGain: 1,
      goldGain: 1,
      dropChance: 1,
      rerollCharges: 0,
      damageTakenMultiplier: 1,
    },
  },
];

export const ULT_CORE_ID = "ult_core";

export function classById(id: ClassId): ClassDef {
  return CLASSES.find((c) => c.id === id)!;
}

export function ultLevel(waveIndex: number, bonus: number): number {
  const auto = Math.floor(Math.max(0, waveIndex - 1) / 3);
  return 1 + auto + bonus;
}

export function ultPower(waveIndex: number, bonus: number) {
  const level = ultLevel(waveIndex, bonus);
  return {
    level,
    novaRadius: 88 + level * 30,
    novaDamage: 38 + level * 24,
    beamLength: 360 + level * 90,
    beamWidth: 16 + level * 3,
    beamDamage: 52 + level * 32,
    zoneRadius: 68 + level * 20,
    zoneDuration: 2.1 + level * 0.35,
    zoneDps: 16 + level * 11,
    zoneSlow: Math.min(0.7, 0.4 + level * 0.05),
    cooldown: Math.max(5.5, 15.5 - level * 1.15),
    chargeFromDamage: 0.0032 + level * 0.00035,
  };
}
